server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@discovery-server:8761/eureka/




      