zuul:
  prefix: /
  ignoredServices: '*'
  routes:
    vets-service: jobs/**
    visits-service: companies/**
    review-service: reviews/**
    api-gateway: gateway/**
    discovery-server : eureka/web
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: docker
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@discovery-server:8761/eureka