
﻿spring:
  config:
    activate:
      on-profile: mysql
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@localhost:8761/eureka
      
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin: 
    tracing: 
      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  datasource:
    url: jdbc:mysql://mydb-mariadb:3306?useSSL=false
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@discovery-server:8761/eureka




