spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
  serviceUrl:
    defaultZone: http://admin:123456Ax@dlocalhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@discovery-server:8761/eureka/