spring:
  config:
    activate:
      on-profile: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
  serviceUrl:
      defaultZone: http://admin:123456Ax@localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin: 
    tracing: 
      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: docker,postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
      
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456Ax@discovery-server:8761/eureka